import NavBar from '@/styles/nav_bar'
import { Montserrat } from 'next/font/google'
import LoginMenu from './login_menu'

const fontMontserrat = Montserrat({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children,}: { children: React.ReactNode}) {
  return (
    <html lang="en">
      <body className={fontMontserrat.className}>
          <NavBar />
          <LoginMenu />
          { children }
        </body>
    </html>
  )
}
